// Generated by CoffeeScript 1.6.3
var QueryError, _ref,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

QueryError = (function(_super) {
  __extends(QueryError, _super);

  function QueryError() {
    _ref = QueryError.__super__.constructor.apply(this, arguments);
    return _ref;
  }

  QueryError.prototype.contructor = function(message) {
    if (message == null) {
      message = "Query Error";
    }
    return QueryError.__super__.contructor.apply(this, arguments);
  };

  return QueryError;

})(Error);
