// Generated by CoffeeScript 1.6.3
"use strict";
var CompositeExpression, Connection;

CompositeExpression = require('./expression/CompositeExpression');

Connection = require('../Connection');

/*
QueryBuilder class is responsible to dynamically create SQL queries.

Important: Verify that every feature you use will work with your database vendor.
SQL Query Builder does not attempt to validate the generated SQL at all.

The query builder does no validation whatsoever if certain features even work with the
underlying database vendor. Limit queries and joins are NOT applied to UPDATE and DELETE statements
even if some vendors such as MySQL support it.
*/


/*
//@ sourceMappingURL=QueryBuilder.map
*/
