// Generated by CoffeeScript 1.6.3
var Connection;

Connection = (function() {
  function Connection() {}

  return Connection;

})();

module.exports = Connection;

/*
//@ sourceMappingURL=Connection.map
*/
