// Generated by CoffeeScript 1.6.3
"use strict";
var dbal;

dbal = {
  query: {
    expression: {
      CompositeExpression: require('./query/expression/CompositeExpression')
    }
  }
};

module.exports = dbal;

/*
//@ sourceMappingURL=dbal.map
*/
